### ISSUE TITLE
No way to run two services from idea

### ISSUE THREAD

**Issue by R-Rajkumar** [ballerinalang/plugin-intellij#466]
When I start my second service, it gives an error "ballerina: address already in use"

**Comment by Shan1024** [comment]
@R-Rajkumar: This is not an issue in IDEA plugin, the reason for this is the second service also tries to start using the port 9090 which is already used by the first service. AFAIK, you can change ports using configs in http package. Can you try that?

**Comment by R-Rajkumar** [comment]
@Shan1024 When I run multiple services in Composer, all the services start on port 9090. I expect the same behavior in idea as well.

**Comment by Shan1024** [comment]
@R-Rajkumar: I just tried with the composer to verify that it can only run a single file at a time. But anyway we can **redeploy** service(s) in a file which will stop the current service and start the new service if the file is different. So basically it is like **restart**. So in the IDEA you have two options. 

1. If you have already started a service(which uses some port), **you have to stop it before starting another service which uses the same port** or **you can restart the currently deployed services**(I guess this is what you are looking for, please refer to the screenshot below). You can deploy **services in a single file**(which will deploy all services in the current file) as well as **services in a package**(deploy all services in a package) as well.

![selection_158](https://user-images.githubusercontent.com/4003115/27805245-459b5872-6051-11e7-888a-88b5cbf163a7.png)

2. Using **Single Instance** mode.

![run-debug configurations_159](https://user-images.githubusercontent.com/4003115/27805658-9d1bd39a-6053-11e7-9c2a-d8bb265ece56.png)

In this mode, if you have deployed the services in a file/package and if you later try to start the services which matches current run configurations, IDEA will ask you to to stop the currently running services(identifies using run configurations) before deploying services again. 

![selection_160](https://user-images.githubusercontent.com/4003115/27805728-0c55dbca-6054-11e7-9e34-3a0f4b0460b9.png)

But if you try to start services which does not match the current run configurations, you will get the same "Address already in use" message. In that case, use the above method to stop the current service and start new services.

We can observe the same behavior with Java applications (Eg - msf4j service) started with IDEA. If you have already started a service in port 9090, you cant start another service until you have stopped the all other running services which uses port 9090. IDEA does not automatically stop any running instances unless you have enabled **Single Instance** mode. This is the expected behavior of IDEA since user has more control over their actions. Please let me know if you facing a different issue than what I understood here.

**Comment by R-Rajkumar** [comment]
@Shan1024, thanks for the detailed explanation. I had several services in different files, but I haven't put them into packages. So they are in default package. Two files in default packages are not considered to be in the same package in Ballerina, that explains why I was not able to start all my services in idea at the same time (apparently it seems I put all of them into a same package and ran it form composer and it was working). So we can close this, not a bug.
