### ISSUE TITLE
[Doc] Add Link to plugin documentation from the ballerina site

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/plugin-intellij#631]
https://ballerinalang.org/docs/ doesn't have any information about the idea plugin usage. We can add this information to the website or we can point to the Git ReadMe.

**Comment by Shan1024** [comment]
Hi @yasassri,

AFAIU, the docs section is dedicated for the language documentations. So I guess it is wrong to add the details of the plugin to it.

 IDEA is a product of JetBrains and anyone can work with the Ballerina plugin if they are familiar with IDEA. If they are not familiar with the IDEA, they can always refer the JetBrains website for more details. If someone specifically need any help regarding the plugin, they can refer the [Getting Started](https://github.com/ballerinalang/plugin-intellij/tree/master/getting-started) section which explains some of the topics which can be useful to users.

**Comment by yasassri** [comment]
Hi @Shan1024 , 

Let's consider an external person who is willing to use ballerina. When he goes to the website, it doesn't have any documentation on plugins or tools support for ballerina. Only when you go to download page you get to know that there is an Idea plugin. IMO we should at least link the Git documentation from the main website, may be from the Download page. Kotlin maintains a great website where their site is a one-stop shop for all information.

**Comment by Shan1024** [comment]
Hi @yasassri,

> Only when you go to download page you get to know that there is an Idea plugin

This is not true actually. When you create a new **bal** file or open a **bal** file, IDEA suggest you to install the Ballerina plugin. Usually when a developers try a new programming language, they definitely check whether there are any plugin available for their favorite IDE. They can do this through the IDE without ever visiting the language's website.

In Kotlin's case, it is also developed by the JetBrains. So it is perfectly normal for them to include IDEA plugin tutorials or any other materials related to that because IDEA is their product as well.

Anyway, this is not a issue in the plugin or cannot be fixed in this repo. Hence I'll close this. Please create an issue in [website](https://github.com/ballerinalang/website) repo if you strongly feel this should be added to the docs section in the website.
