### ISSUE TITLE
[Doc] What is the compatible version of the plugin for ballerina versions

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/plugin-intellij#632]
When I browse through https://plugins.jetbrains.com/plugin/9520-ballerina The versioning seems to be different from the Ballerina version. Is it possible to mention which plugin version supports which ballerina version? It seems 0.91 = 0.9.1

**Comment by Shan1024** [comment]
Hi @yasassri,

The plugin version and the Ballerina versions are different. Latest plugin will support latest Ballerina runtime unless stated otherwise. If the plugin adds support to a new Ballerina version, it will be added to the change log like below screenshot.

![selection_244](https://user-images.githubusercontent.com/4003115/31336718-b31254c6-ad15-11e7-8380-de64e82a8633.png)
