### ISSUE TITLE
When you have multiple compiler issues the auto import does not work in Intellij plugin

### ISSUE THREAD

**Issue by SupunS** [ballerinalang/plugin-intellij#658]
Please refer https://github.com/ballerinalang/ballerina/issues/2817 for more details

**Comment by Shan1024** [comment]
Auto import does not work when there are syntax changes since it can cause issues when identifying the necessary package to import. So moving the caret to the package name to be imported and pressing  `Alt + Enter` will show a popup with the package names. You can use that to import packages without any issue.
